### PR TITLE
Add support for Android-O Background Limitations

### PR DESCRIPTION
**Pull request by ogeidix**
This commit updates the Google Play services execution strategy
to support Android-O Background Services Limitations.
https://developer.android.com/preview/features/background.html#services

Unfortunately this change includes additional fixes that have been made
in the internal repo, but not synced timely.
In future we will pay more attention to push each commit atomically.

### CODE REVIEW

**Comment by doom777** [comment]
so... take back this pull-request, make another fork from the source, add only the required changes, and submit a new pull request. obviously no-one is going to accept a pull request that changes too much

**Comment by JakeWharton** [comment]
You didn't read the PR description, did you?

**Comment by ogeidix** [comment]
Apparently org.junit.Assert.assertThrows has been introduces in junit 4.13,
which has not been released yet :(

I am going to revert assertThrows() to expectedException.expect()
and force push the update on top of this branch.

Sorry for the not clear pull request.
Need to do it in this way to sync with the internal repo, future pull requests will be handled better.

**Comment by ogeidix** [comment]
Also, I will not bump the version in this pull request, but I will create a new one to set version = 0.6.0

Not exactly how I would like to do it, hopefully that will be the last "not great" move of the day.

**Pull request merged**
