### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by buojira**
The project I am workking did not have the 'jcenter()' repository, so I lost some time until found out why the project was not compiling. This note might save some time of someone else.

### CODE REVIEW

**Comment by buojira** [comment]
I signed it!

**Comment by FabianTerhorst** [comment]
Why you added ```mavenCentral()```?

**Comment by FabianTerhorst** [comment]
something like this should be more then enough 
```groovy
compile 'com.firebase:firebase-jobdispatcher:0.8.1'
...
repositories {
    jcenter()
}
```

**Comment by buojira** [comment]
My mistake. The mavenCentral() would cause confusion

**Comment by samtstern** [comment]
In April 2019 we announced that Firebase Job Dispatcher would be deprecated today, April 7th 2020.  For this reason we are going to close all open issues and archive the repository.  We will also stop supporting FJD for new app installations (such as those targeting sdk versions greater than Android Q).  Existing apps that rely on FJD should continue to function as usual.

While we will no longer work on FJD, we encourage you to [migrate to Work Manager](https://developer.android.com/topic/libraries/architecture/workmanager/migrating-fb) which is a superior tool and fully supported by the Android team.

Thank you for taking the time to try the library and improve it with this Pull Request.  We sincerely appreciate your effort and we apologize for not addressing it in time.

**Pull request closed without merging**
