### PR TITLE
Exposed method isJobRunning to client for checking job is running or …

### PR DESCRIPTION
**Pull request by HimanshuNarang**
…not.

### CODE REVIEW

**Review by HimanshuNarang — COMMENTED** [review]
Please review my changes.

**Comment by HimanshuNarang** [comment]
@SUPERCILEX 
Please Review my changes.

**Comment by SUPERCILEX** [comment]
I'm not a maintainer and this repo is constantly abandoned 😢. I got them to merge my stuff by contacting support.

**Comment by HimanshuNarang** [comment]
@ciarand 
Please review or let me know the  maintainer

**Comment by HimanshuNarang** [comment]
@SUPERCILEX  How can I contact to support of this particular repository?

**Comment by SUPERCILEX** [comment]
Contact Firebase support and tell them they're ignoring this repo (again) and that you're annoyed. That's basically what I had to do... Every single time I wanted to merge something. 🤦‍♂️

**Review by eLmistiso — APPROVED** [review]

**Comment by samtstern** [comment]
In April 2019 we announced that Firebase Job Dispatcher would be deprecated today, April 7th 2020.  For this reason we are going to close all open issues and archive the repository.  We will also stop supporting FJD for new app installations (such as those targeting sdk versions greater than Android Q).  Existing apps that rely on FJD should continue to function as usual.

While we will no longer work on FJD, we encourage you to [migrate to Work Manager](https://developer.android.com/topic/libraries/architecture/workmanager/migrating-fb) which is a superior tool and fully supported by the Android team.

Thank you for taking the time to try the library and improve it with this Pull Request.  We sincerely appreciate your effort and we apologize for not addressing it in time.

**Pull request closed without merging**
