### PR TITLE
Fix travis

### PR DESCRIPTION
**Pull request by SUPERCILEX**

### CODE REVIEW

**Comment by SUPERCILEX** [comment]
I've encountered 137 before, we'll see if this works.

**Comment by SUPERCILEX** [comment]
Voilà! Also, why is the target SDK 23?

**Comment by ciarand** [comment]
The latest publicly available API was 23 when the project was initially started, though we should probably update that.

PRs welcome, otherwise we'll probably get to it soonish. :+1:

**Comment by SUPERCILEX** [comment]
Awesome and I see you added the Travis stuff in your own PR so I'm closing this one.

**Pull request closed without merging**
