### PR TITLE
Add JCenter artifacts, cleanup docs

### PR DESCRIPTION
**Pull request by ciarand**
The commit messages have more details, but this PR:

- Adds clear build variants (withGcmDep / noDep)
- Adds JCenter uploads
- Cleans up the README

### CODE REVIEW

**Comment by SUPERCILEX** [comment]
Awesome!!! Can't wait for the merge!

**Comment by SUPERCILEX** [comment]
@ciarand pull from #39.

**Comment by SUPERCILEX** [comment]
@ciarand that's not going to work, see #39.

**Comment by SUPERCILEX** [comment]
Normal Travis builds have 4GB of RAM, sudo builds have 7.5Gbs.

**Comment by ciarand** [comment]
Thanks. That's a pretty gross use of sudo, but whatever works. Updated commit incoming.

**Comment by SUPERCILEX** [comment]
You're welcome!

**Comment by ciarand** [comment]
:sparkles:

**Comment by SUPERCILEX** [comment]
🎊 👍

**Pull request merged**
