### PR TITLE
README code example for recurring job

### PR DESCRIPTION
**Pull request by sid6mathur**
Simple edit to README to show recurring job (fixes Issue #22)

### CODE REVIEW

**Comment by simathur** [comment]
I signed the Individual CLA.

**Comment by NathanHallTransloc** [comment]
This provides clarity where there otherwise is none. It should be merged for the good of future users.

**Comment by sreekanth-krishnan** [comment]
Is it possible to use this method to run a job at 7am each day? I find this **Trigger.executionWindow** a little confusing. Any insight on this is highly appreciated.

**Comment by patloew** [comment]
I think your example in the README is wrong, if you look at `writeExecutionWindowTriggerToBundle()` in `GooglePlayJobWriter`.

```
if (job.isRecurring()) {
  b.putLong(REQUEST_PARAM_TRIGGER_WINDOW_PERIOD, trigger.getWindowEnd());
  b.putLong(REQUEST_PARAM_TRIGGER_WINDOW_FLEX, trigger.getWindowEnd() - trigger.getWindowStart());
}
```

According to this, the `period` should be provided in `windowEnd` and `period-flex` should be provided in `windowStart`. Therefore the correct call would be `Trigger.executionWindow(period-flex, period)`.

Or, as a small util method:

```
public static JobTrigger createPeriodicTrigger(int period, int flex) {
  return Trigger.executionWindow(period-flex, period);
}
```

**Comment by Gaket** [comment]
According to docs:

>  @param windowStart The earliest time (in seconds) the job should be considered eligible to run.
Calculated from when the job was scheduled (for new jobs) or last run (for recurring jobs).

For example, we want to run a job once a day. We set a window (23hours, 24hours). So after each run it will go up to 1 hour less. In two -three months we will be probably back for a day.

**Comment by hannesa2** [comment]
because your PR has conflicts and your origin branch is gone 
image

I made a copy of your useful changes and made this PR to have a chance to get this merged

**Comment by samtstern** [comment]
In April 2019 we announced that Firebase Job Dispatcher would be deprecated today, April 7th 2020.  For this reason we are going to close all open issues and archive the repository.  We will also stop supporting FJD for new app installations (such as those targeting sdk versions greater than Android Q).  Existing apps that rely on FJD should continue to function as usual.

While we will no longer work on FJD, we encourage you to [migrate to Work Manager](https://developer.android.com/topic/libraries/architecture/workmanager/migrating-fb) which is a superior tool and fully supported by the Android team.

Thank you for taking the time to try the library and improve it with this Pull Request.  We sincerely appreciate your effort and we apologize for not addressing it in time.

**Pull request closed without merging**
